### ISSUE TITLE
Does not autoplay on google chrome.

### ISSUE THREAD

**Issue by jeange1003** [mdn/violent-theremin#8]
In console: app.js:3 The AudioContext was not allowed to start. It must be resume (or created) after a user gesture on the page. https://goo.gl/7K7WLu

**Comment by chrisdavidmills** [comment]
Ah, this is due to Chrome's new audio autoplay policy. I've added in a fix - let me know if you think this looks OK: http://mdn.github.io/violent-theremin/

**Comment by jeange1003** [comment]
It works well, thank you.
